<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Ingredient;
use App\Models\MenuItem;
use App\Models\Recipe;
use App\Models\Supplier;
use App\Models\Wastage;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /** Mirrors resources/js/inventory/demo-data.js exactly. */
    public function run(): void
    {
        $rows = [
            ['code' => 'ING-001', 'name' => 'Basmati Rice', 'cat' => 'Grains & Rice', 'unit' => 'KG', 'cur' => 42, 'min' => 15, 'reorder' => 25, 'cost' => 95, 'sup' => 'Bengal Food Supplies', 'loc' => 'Dry Store'],
            ['code' => 'ING-002', 'name' => 'Chicken', 'cat' => 'Meat & Poultry', 'unit' => 'KG', 'cur' => 8, 'min' => 20, 'reorder' => 30, 'cost' => 210, 'sup' => 'Fresh Chicken Traders', 'loc' => 'Cold Storage'],
            ['code' => 'ING-003', 'name' => 'Mutton', 'cat' => 'Meat & Poultry', 'unit' => 'KG', 'cur' => 14, 'min' => 10, 'reorder' => 15, 'cost' => 620, 'sup' => 'Fresh Chicken Traders', 'loc' => 'Freezer'],
            ['code' => 'ING-004', 'name' => 'Onion', 'cat' => 'Vegetables', 'unit' => 'KG', 'cur' => 3, 'min' => 15, 'reorder' => 25, 'cost' => 32, 'sup' => 'Kolkata Vegetable Market', 'loc' => 'Dry Store'],
            ['code' => 'ING-005', 'name' => 'Tomato', 'cat' => 'Vegetables', 'unit' => 'KG', 'cur' => 18, 'min' => 10, 'reorder' => 15, 'cost' => 28, 'sup' => 'Kolkata Vegetable Market', 'loc' => 'Dry Store'],
            ['code' => 'ING-006', 'name' => 'Cooking Oil', 'cat' => 'Oil & Fats', 'unit' => 'LITRE', 'cur' => 22, 'min' => 10, 'reorder' => 15, 'cost' => 145, 'sup' => 'Bengal Food Supplies', 'loc' => 'Dry Store'],
            ['code' => 'ING-007', 'name' => 'Paneer', 'cat' => 'Dairy', 'unit' => 'KG', 'cur' => 6, 'min' => 8, 'reorder' => 12, 'cost' => 320, 'sup' => 'Bengal Food Supplies', 'loc' => 'Cold Storage'],
            ['code' => 'ING-008', 'name' => 'Flour', 'cat' => 'Bakery', 'unit' => 'KG', 'cur' => 30, 'min' => 12, 'reorder' => 20, 'cost' => 42, 'sup' => 'Bengal Food Supplies', 'loc' => 'Dry Store'],
            ['code' => 'ING-009', 'name' => 'Egg', 'cat' => 'Dairy', 'unit' => 'PCS', 'cur' => 0, 'min' => 60, 'reorder' => 120, 'cost' => 6, 'sup' => 'Bengal Food Supplies', 'loc' => 'Cold Storage'],
            ['code' => 'ING-010', 'name' => 'Coke', 'cat' => 'Beverages', 'unit' => 'BOTTLE', 'cur' => 48, 'min' => 24, 'reorder' => 48, 'cost' => 38, 'sup' => 'Eastern Beverage Distributors', 'loc' => 'Bar Store'],
            ['code' => 'ING-011', 'name' => 'Spices', 'cat' => 'Spices', 'unit' => 'KG', 'cur' => 9, 'min' => 4, 'reorder' => 6, 'cost' => 480, 'sup' => 'Bengal Food Supplies', 'loc' => 'Dry Store'],
            ['code' => 'ING-012', 'name' => 'Milk', 'cat' => 'Dairy', 'unit' => 'LITRE', 'cur' => 5, 'min' => 10, 'reorder' => 15, 'cost' => 58, 'sup' => 'Bengal Food Supplies', 'loc' => 'Cold Storage'],
        ];

        $ingredients = [];
        foreach ($rows as $row) {
            $ingredients[$row['name']] = Ingredient::firstOrCreate(
                ['code' => $row['code']],
                [
                    'name' => $row['name'], 'category' => $row['cat'], 'unit' => $row['unit'],
                    'current_stock' => $row['cur'], 'min_stock' => $row['min'], 'reorder_level' => $row['reorder'],
                    'avg_cost' => $row['cost'], 'supplier_id' => Supplier::where('name', $row['sup'])->value('id'),
                    'storage_location' => $row['loc'],
                ]
            );
        }

        // Recipes / BOM — mirrors RECIPES in the same file.
        $recipeSeed = [
            'Chicken Biryani' => [['Basmati Rice', 0.25, 'KG'], ['Chicken', 0.2, 'KG'], ['Onion', 0.08, 'KG'], ['Cooking Oil', 0.03, 'LITRE'], ['Spices', 0.015, 'KG']],
            'Butter Chicken' => [['Chicken', 0.22, 'KG'], ['Tomato', 0.15, 'KG'], ['Milk', 0.05, 'LITRE'], ['Spices', 0.02, 'KG']],
        ];
        foreach ($recipeSeed as $itemName => $lines) {
            $menuItem = MenuItem::where('name', $itemName)->first();
            if (! $menuItem) {
                continue;
            }
            $recipe = Recipe::firstOrCreate(['menu_item_id' => $menuItem->id]);
            foreach ($lines as [$ingName, $qty, $unit]) {
                if (isset($ingredients[$ingName])) {
                    $recipe->lines()->firstOrCreate(['ingredient_id' => $ingredients[$ingName]->id], ['qty' => $qty, 'unit' => $unit]);
                }
            }
        }

        // A representative slice of the stock ledger (full transaction history would be generated by real usage).
        $sourav = Employee::where('employee_code', 'EMP-009')->first();
        $ledgerSeed = [
            ['Basmati Rice', 'OPENING', '—', 0, 50, 50],
            ['Basmati Rice', 'CONSUMPTION', 'ORD-1028', 50, -8, 42],
            ['Chicken', 'PURCHASE', 'GRN-2026-0042', 4, 20, 24],
            ['Chicken', 'CONSUMPTION', 'ORD-1041', 24, -16, 8],
            ['Onion', 'WASTAGE', 'WST-014', 20, -2, 18],
            ['Onion', 'CONSUMPTION', 'ORD-1035', 18, -15, 3],
            ['Egg', 'PURCHASE', 'GRN-2026-0038', 40, 120, 160],
            ['Egg', 'CONSUMPTION', 'ORD-1019', 160, -160, 0],
            ['Milk', 'ADJUSTMENT', 'ADJ-006', 8, -3, 5],
        ];
        foreach ($ledgerSeed as [$ingName, $type, $ref, $prev, $change, $next]) {
            if (isset($ingredients[$ingName])) {
                $ingredients[$ingName]->ledgerEntries()->create([
                    'type' => $type, 'reference' => $ref, 'previous_qty' => $prev, 'change_qty' => $change,
                    'new_qty' => $next, 'employee_id' => $sourav?->id, 'recorded_at' => now(),
                ]);
            }
        }

        $wastageSeed = [
            ['WST-014', 'Onion', 2, 'Spoiled', 64, 'Arjun Das'],
            ['WST-015', 'Paneer', 0.5, 'Overcooked', 160, 'Chef Imran'],
            ['WST-016', 'Tomato', 1.2, 'Preparation Waste', 34, 'Chef Imran'],
        ];
        foreach ($wastageSeed as [$code, $ingName, $qty, $reason, $cost, $empName]) {
            if (isset($ingredients[$ingName])) {
                Wastage::firstOrCreate(['code' => $code], [
                    'ingredient_id' => $ingredients[$ingName]->id, 'qty' => $qty, 'unit' => $ingredients[$ingName]->unit,
                    'reason' => $reason, 'cost' => $cost, 'employee_id' => Employee::where('name', $empName)->value('id'),
                    'date' => now()->toDateString(),
                ]);
            }
        }
    }
}
