<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login')->name('home');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.attempt');
    Route::view('/forgot-password', 'auth.forgot-password')->name('password.request');
    Route::view('/reset-password', 'auth.reset-password')->name('password.reset');
});

Route::match(['get', 'post'], '/logout', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware('auth')
    ->name('logout');

Route::middleware('auth')->group(function () {
    Route::get('/change-password', [PasswordController::class, 'edit'])->name('password.change');
    Route::put('/change-password', [PasswordController::class, 'update'])->name('password.update');
    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::view('/pos', 'pos')->middleware('permission:POS,View')->name('pos');
    Route::view('/tables', 'tables')->middleware('permission:Orders,View')->name('tables');
    Route::view('/kds', 'kds')->middleware('permission:Kitchen,View')->name('kds');
    Route::get('/billing', [BillingController::class, 'index'])->middleware('permission:Billing,View')->name('billing');
    Route::get('/billing/data', [BillingController::class, 'data'])->middleware('permission:Billing,View')->name('billing.data');
    Route::patch('/billing/invoices/{invoice}/discount', [BillingController::class, 'discount'])->middleware('permission:Billing,Edit')->name('billing.discount');
    Route::patch('/billing/invoices/{invoice}/adjustments', [BillingController::class, 'adjustments'])->middleware('permission:Billing,Edit')->name('billing.adjustments');
    Route::post('/billing/invoices/{invoice}/coupon', [BillingController::class, 'applyCoupon'])->middleware('permission:Billing,Edit')->name('billing.coupon.apply');
    Route::delete('/billing/invoices/{invoice}/coupon', [BillingController::class, 'removeCoupon'])->middleware('permission:Billing,Edit')->name('billing.coupon.remove');
    Route::patch('/billing/items/{item}', [BillingController::class, 'item'])->middleware('permission:Billing,Edit')->name('billing.items');
    Route::post('/billing/invoices/{invoice}/payments', [BillingController::class, 'payment'])->middleware('permission:Billing,Create')->name('billing.payments');
    Route::post('/billing/invoices/{invoice}/complete', [BillingController::class, 'complete'])->middleware('permission:Billing,Create')->name('billing.complete');
    Route::post('/billing/invoices/{invoice}/refunds', [BillingController::class, 'refund'])->middleware('permission:Billing,Cancel')->name('billing.refunds');
    Route::post('/billing/invoices/{invoice}/void', [BillingController::class, 'void'])->middleware('permission:Billing,Cancel')->name('billing.void');
    Route::post('/billing/invoices/{invoice}/close', [BillingController::class, 'close'])->middleware('permission:Billing,Edit')->name('billing.close');
    Route::view('/reservations', 'reservations')->middleware('permission:Orders,View')->name('reservations');
    Route::get('/customers', [CustomerController::class, 'index'])->middleware('permission:Customers,View')->name('customers');
    Route::get('/customers/data', [CustomerController::class, 'data'])->middleware('permission:Customers,View')->name('customers.data');
    Route::post('/customers', [CustomerController::class, 'store'])->middleware('permission:Customers,Create')->name('customers.store');
    Route::post('/customers/coupons', [CustomerController::class, 'storeCoupon'])->middleware('permission:Customers,Create')->name('customers.coupons.store');
    Route::put('/customers/coupons/{coupon}', [CustomerController::class, 'updateCoupon'])->middleware('permission:Customers,Edit')->name('customers.coupons.update');
    Route::delete('/customers/coupons/{coupon}', [CustomerController::class, 'destroyCoupon'])->middleware('permission:Customers,Edit')->name('customers.coupons.destroy');
    Route::put('/customers/{customer}', [CustomerController::class, 'update'])->middleware('permission:Customers,Edit')->name('customers.update');
    Route::patch('/customers/{customer}/vip', [CustomerController::class, 'vip'])->middleware('permission:Customers,Edit')->name('customers.vip');
    Route::patch('/customers/{customer}/loyalty', [CustomerController::class, 'loyalty'])->middleware('permission:Customers,Edit')->name('customers.loyalty');
    Route::patch('/customers/{customer}/note', [CustomerController::class, 'note'])->middleware('permission:Customers,Edit')->name('customers.note');
    Route::get('/menu', [MenuController::class, 'index'])->middleware('permission:Menu,View')->name('menu');
    Route::get('/menu/data', [MenuController::class, 'data'])->middleware('permission:Menu,View')->name('menu.data');
    Route::post('/menu/items', [MenuController::class, 'storeItem'])->middleware('permission:Menu,Create')->name('menu.items.store');
    Route::put('/menu/items/{item}', [MenuController::class, 'updateItem'])->middleware('permission:Menu,Edit')->name('menu.items.update');
    Route::patch('/menu/items/{item}/availability', [MenuController::class, 'availability'])->middleware('permission:Menu,Edit')->name('menu.items.availability');
    Route::post('/menu/items/{item}/duplicate', [MenuController::class, 'duplicate'])->middleware('permission:Menu,Create')->name('menu.items.duplicate');
    Route::post('/menu/categories', [MenuController::class, 'storeCategory'])->middleware('permission:Menu,Create')->name('menu.categories.store');
    Route::put('/menu/categories/{category}', [MenuController::class, 'updateCategory'])->middleware('permission:Menu,Edit')->name('menu.categories.update');
    Route::post('/menu/modifiers', [MenuController::class, 'storeModifier'])->middleware('permission:Menu,Create')->name('menu.modifiers.store');
    Route::put('/menu/modifiers/{group}', [MenuController::class, 'updateModifier'])->middleware('permission:Menu,Edit')->name('menu.modifiers.update');
    Route::post('/menu/combos', [MenuController::class, 'storeCombo'])->middleware('permission:Menu,Create')->name('menu.combos.store');
    Route::put('/menu/combos/{combo}', [MenuController::class, 'updateCombo'])->middleware('permission:Menu,Edit')->name('menu.combos.update');
    Route::get('/inventory', [InventoryController::class, 'index'])->middleware('permission:Inventory,View')->name('inventory');
    Route::get('/inventory/data', [InventoryController::class, 'data'])->middleware('permission:Inventory,View')->name('inventory.data');
    Route::post('/inventory/ingredients', [InventoryController::class, 'storeIngredient'])->middleware('permission:Inventory,Create')->name('inventory.ingredients.store');
    Route::put('/inventory/ingredients/{ingredient}', [InventoryController::class, 'updateIngredient'])->middleware('permission:Inventory,Edit')->name('inventory.ingredients.update');
    Route::delete('/inventory/ingredients/{ingredient}', [InventoryController::class, 'destroyIngredient'])->middleware('permission:Inventory,Edit')->name('inventory.ingredients.destroy');
    Route::patch('/inventory/ingredients/{ingredient}/adjust', [InventoryController::class, 'adjust'])->middleware('permission:Inventory,Edit')->name('inventory.ingredients.adjust');
    Route::post('/inventory/suppliers', [InventoryController::class, 'storeSupplier'])->middleware('permission:Inventory,Create')->name('inventory.suppliers.store');
    Route::put('/inventory/suppliers/{supplier}', [InventoryController::class, 'updateSupplier'])->middleware('permission:Inventory,Edit')->name('inventory.suppliers.update');
    Route::delete('/inventory/suppliers/{supplier}', [InventoryController::class, 'destroySupplier'])->middleware('permission:Inventory,Edit')->name('inventory.suppliers.destroy');
    Route::post('/inventory/wastage', [InventoryController::class, 'storeWastage'])->middleware('permission:Inventory,Create')->name('inventory.wastage.store');
    Route::delete('/inventory/wastage/{wastage}', [InventoryController::class, 'destroyWastage'])->middleware('permission:Inventory,Edit')->name('inventory.wastage.destroy');
    Route::post('/inventory/counts', [InventoryController::class, 'storeCount'])->middleware('permission:Inventory,Approve')->name('inventory.counts.store');
    Route::delete('/inventory/counts/{count}', [InventoryController::class, 'destroyCount'])->middleware('permission:Inventory,Edit')->name('inventory.counts.destroy');
    Route::put('/inventory/recipes/{menuItem}', [InventoryController::class, 'updateRecipe'])->middleware('permission:Inventory,Edit')->name('inventory.recipes.update');
    Route::get('/inventory/export', [InventoryController::class, 'export'])->middleware('permission:Inventory,Export')->name('inventory.export');
    Route::get('/purchases', [PurchaseController::class, 'index'])->middleware('permission:Purchases,View')->name('purchases');
    Route::get('/purchases/data', [PurchaseController::class, 'data'])->middleware('permission:Purchases,View')->name('purchases.data');
    Route::post('/purchases/orders', [PurchaseController::class, 'storeOrder'])->middleware('permission:Purchases,Create')->name('purchases.orders.store');
    Route::put('/purchases/orders/{order}', [PurchaseController::class, 'updateOrder'])->middleware('permission:Purchases,Edit')->name('purchases.orders.update');
    Route::patch('/purchases/orders/{order}/status', [PurchaseController::class, 'status'])->middleware('permission:Purchases,Approve')->name('purchases.orders.status');
    Route::delete('/purchases/orders/{order}', [PurchaseController::class, 'destroyOrder'])->middleware('permission:Purchases,Cancel')->name('purchases.orders.destroy');
    Route::post('/purchases/receipts', [PurchaseController::class, 'storeReceipt'])->middleware('permission:Purchases,Create')->name('purchases.receipts.store');
    Route::delete('/purchases/receipts/{receipt}', [PurchaseController::class, 'destroyReceipt'])->middleware('permission:Purchases,Cancel')->name('purchases.receipts.destroy');
    Route::get('/purchases/export', [PurchaseController::class, 'export'])->middleware('permission:Purchases,Export')->name('purchases.export');
    Route::get('/expenses', [ExpenseController::class, 'index'])->middleware('permission:Expenses,View')->name('expenses');
    Route::get('/expenses/data', [ExpenseController::class, 'data'])->middleware('permission:Expenses,View')->name('expenses.data');
    Route::post('/expenses', [ExpenseController::class, 'store'])->middleware('permission:Expenses,Create')->name('expenses.store');
    Route::put('/expenses/{expense}', [ExpenseController::class, 'update'])->middleware('permission:Expenses,Edit')->name('expenses.update');
    Route::patch('/expenses/{expense}/status', [ExpenseController::class, 'status'])->middleware('permission:Expenses,Approve')->name('expenses.status');
    Route::delete('/expenses/{expense}', [ExpenseController::class, 'destroy'])->middleware('permission:Expenses,Cancel')->name('expenses.destroy');
    Route::get('/expenses/export', [ExpenseController::class, 'export'])->middleware('permission:Expenses,Export')->name('expenses.export');
    Route::get('/reports', [ReportController::class, 'index'])->middleware('permission:Reports,View')->name('reports');
    Route::get('/reports/data', [ReportController::class, 'data'])->middleware('permission:Reports,View')->name('reports.data');
    Route::get('/reports/export/{kind}', [ReportController::class, 'export'])->middleware('permission:Reports,Export')->name('reports.export');
    Route::get('/employees', [EmployeeController::class, 'index'])->middleware('permission:Employees,View')->name('employees');
    Route::get('/employees/data', [EmployeeController::class, 'data'])->middleware('permission:Employees,View')->name('employees.data');
    Route::post('/employees', [EmployeeController::class, 'store'])->middleware('permission:Employees,Create')->name('employees.store');
    Route::put('/employees/{employee}', [EmployeeController::class, 'update'])->middleware('permission:Employees,Edit')->name('employees.update');
    Route::patch('/employees/{employee}/status', [EmployeeController::class, 'status'])->middleware('permission:Employees,Edit')->name('employees.status');
    Route::patch('/employees/{employee}/shift', [EmployeeController::class, 'shift'])->middleware('permission:Employees,Edit')->name('employees.shift');
    Route::patch('/employees/{employee}/permissions', [EmployeeController::class, 'permissions'])->middleware('permission:Employees,Approve')->name('employees.permissions');
    Route::get('/settings', [SettingController::class, 'index'])->middleware('permission:Settings,View')->name('settings');
    Route::get('/settings/data', [SettingController::class, 'data'])->middleware('permission:Settings,View')->name('settings.data');
    Route::put('/settings/{section}', [SettingController::class, 'update'])->middleware('permission:Settings,Edit')->name('settings.update');
    Route::delete('/settings/{section}', [SettingController::class, 'reset'])->middleware('permission:Settings,Edit')->name('settings.reset');
});
